### ISSUE TITLE
File not found: param.txt

### ISSUE THREAD

**Issue by noguchikaze** [gfxdisp/Blender-addon-light-field-camera#1]
Blender crashed right after I clicked the "Render Light Field" button.
The error message is 
FileNotFoundError: [Errno2] No such file or directory '/tmp \\ param.txt'
![image](https://user-images.githubusercontent.com/34036852/94761396-7f170880-03d7-11eb-89b5-3cd6081305e4.png)

**Comment by CanCanZeng** [comment]
Hi @noguchikaze , my blender also crash when rendering images. But I do not find thes logs, how do you find these logs?
By the way, I find that in most cases, I can render images in the first time, but the software will crash when I push `render lightfield` button the second time.
Have you solved this problem?

**Comment by DarwinSenior** [comment]
@noguchikaze, sorry for the late reply. I believe you are using the windows system which I have not yet tested. I modified to a sane default which should now also works on windows too. However, you probably should modify the path if you want to specify where the results will be generated.
