### ISSUE TITLE
Where are the rendered results saved?

### ISSUE THREAD

**Issue by SimronThapa** [gfxdisp/Blender-addon-light-field-camera#3]
Hi, 

I was able to install this add-on in my blender 2.9 successfully and could follow all the steps till the last step: click the "Render light field" button. I can see the animation happening in my blender. However, I cannot find the rendered images saved anywhere. When I tried to save manually, only the last frame is saved. How do I save all the 25 images (if 5x5 lens array)? Also, how do I save the disparity map and any data I could generate like a true depth map. Where are the rendered images saved when I click the render light-field button? Please help me figure out this.

**Comment by DarwinSenior** [comment]
close this as this is the same as issue #4.
